feat: application support cros setting
Byzanteam/application-chart-template pull request #6
Opened 2023-09-07 08:53 UTC by YkeLit

2023-09-07 14:20 UTC, fahchen requested changes

2023-09-07 14:20 UTC, fahchen commented on README.md
> +| crossDomainSetting.headers[0] | string | `"*"` |  |
```suggestion
| crossDomainSetting.headers | string[] | `["*"]` |  |
```

2023-09-07 14:20 UTC, fahchen commented on README.md
> +| crossDomainSetting.methods[0] | string | `"GET"` |  |
```suggestion
| crossDomainSetting.methods| string[] | `["GET", ...]` |  |
```

2023-09-07 14:20 UTC, fahchen commented on README.md
> +| crossDomainSetting.originList[0] | string | `"*"` |  |
我觉得这个给默认值，安全性比较低

2023-09-07 14:20 UTC, fahchen commented on templates/traefik/cros.yaml
cors 写错好几遍了，你查查全写吧

2023-09-07 14:20 UTC, fahchen commented on templates/traefik/cros.yaml
> +    accessControlMaxAge: {{ $.Values.crossDomainSetting.maxAge }}
这几个 value的名字就和本身的名字对齐吧

2023-09-07 14:20 UTC, fahchen commented on values.yaml
> +crossDomainSetting: {}
你这里的默认值和 readme 里面学得不一致啊？

2023-09-08 06:51 UTC, fahchen commented
pr title 有错别字

2023-09-08 06:53 UTC, fahchen requested changes

2023-09-08 06:53 UTC, fahchen commented on README.md
> +| corsSetting | object | `{}` |  |
```suggestion
| corsSettings | object | `{}` |  |
```

2023-09-08 08:05 UTC, fahchen requested changes

2023-09-08 08:05 UTC, fahchen commented on tests/values/test.yaml
> +# 需要使用 initcontainers 请配置此项
```suggestion
```

2023-09-08 09:29 UTC, fahchen commented on values.yaml
> +#       - cors-header
我们有这个 middleware 吗？

2023-09-08 10:07 UTC, YkeLit commented on values.yaml
> +#       - cors-header
有这个

2023-09-08 11:06 UTC, fahchen commented on values.yaml
> +#       - cors-header
在哪个文件用到的，贴一下链接呢

2023-09-08 12:11 UTC, YkeLit commented on values.yaml
> +#       - cors-header
https://github.com/Byzanteam/application-chart-template/blob/main/templates/external-services/middlewares/cors-header.yaml
这里

2023-09-08 13:59 UTC, fahchen commented on values.yaml
> +#       - cors-header
这个和现在这个 pr 的用途有什么区别啊

2023-09-08 14:56 UTC, YkeLit commented on values.yaml
> +#       - cors-header
这个是前端用的，现在这个是给后端开放跨域的

2023-09-09 01:06 UTC, fahchen commented on values.yaml
> +#       - cors-header
在 readme 中说明一下

2023-09-10 05:59 UTC, YkeLit commented on values.yaml
> +#       - cors-header
@fahchen 添加上了

2023-09-10 06:19 UTC, fahchen approved these changes

2023-09-10 06:19 UTC, merged